# -*- coding: utf-8 -*-
"""mllabexp2_polynomial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XqnN8NlTlKE-N7v8qbZIbbqB3ebVM4yq
"""

import pandas as pd
data=pd.read_csv("/content/glass.csv")

x=data[["RI",	"Na",	"Mg",	"Al",	"Si"	,"K",	"Ca",	"Ba",	"Fe"]]
y=data["Type"]
replacements = {1:"Windows", 2:"Windows-nonFlat",3:"vehicle",7:"Headlamps",6:"TableWare", 5:'Containers',4:"Vehicle-nonFlat"}
replacer = replacements.get  # For faster gets.

y=[replacer(n, n) for n in y]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=42)
from sklearn.svm import SVC
ml=SVC(C=0.8,kernel="poly")
ml=ml.fit(X_train,y_train)
res=ml.predict(X_test)
from sklearn.metrics import accuracy_score
print("Accuracy=",(accuracy_score(y_test, res)*100))
from sklearn.metrics import classification_report
print(classification_report(y_test, res))