# -*- coding: utf-8 -*-
"""mllabexp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XqnN8NlTlKE-N7v8qbZIbbqB3ebVM4yq
"""

from sklearn.datasets import load_iris
file=load_iris()
x=file.data
y=file.target
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.svm import SVC
ml=SVC(C=0.8,kernel="poly")
ml=ml.fit(x_train,y_train)
result=ml.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, result)*100)